### ISSUE TITLE
Error: no server specified

### ISSUE THREAD

**Issue by davinder2385** [bitnami/bitnami-docker-service-catalog#3]
**Description**

running the image using  docker desktop

**Steps to reproduce the issue:**

1. Dowload image using - docker pull bitnami/service-catalog
2. Run a container using docker desktop

**Describe the results you received:**

Upgrade

davinder2385

test11111
bitnami/service-catalog:latest
EXITED (1)

Error: no server specified

This is an all-in-one binary that can run any of the various Kubernetes

service-catalog servers.

Usage

service-catalog <server> [flags]

Servers

webhook

The Service Catalog Webhook server which manages fields defaulting and

validating of the Service Catalog CRDs.

controller-manager

The service-catalog controller manager is a daemon that embeds the core

control loops shipped with the service catalog.

cleaner

The cleaner asserts all CRD will be removed before removing helm release, it

also removes all finalizers from CRs

migration

The migration tool migrates Service Catalog resources from API Server

(0.2.x) to CRDs (0.3.0) version

Call 'service-catalog --make-symlinks' to create symlinks for each server in the local directory.

Call 'service-catalog <server> --help' for help on a specific server.

Search...
Stick to bottom

**Describe the results you expected:**

Successful start up

**Additional information you deem important (e.g. issue happens only occasionally):**None

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.19.7
  StackAPI:         Unknown
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 45
  Running: 38
  Paused: 0
  Stopped: 7
 Images: 39
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.36GiB
 Name: docker-desktop
 ID: HJ6K:66ZP:657B:KEPT:TWGR:GSY4:GWFE:EAXF:2MP2:34OO:EZGP:NLUB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

NA

**Comment by miguelaeh** [comment]
Hi @davinder2385 ,
It seems you need to pass some parameters. The image log is showing you the `help` of how to use it
